version: '3.0'
services:
  mongodb:
    image: mongo
    container_name: ecommercemongo
    volumes:
      - ./data:/data/db

    ports:
      - 27017:27017
    restart: always
    env_file:
      - .env